baseurl = "http://swalloow.github.io/"
copyright = "All rights reserved - 2017"
disqusshortname = "swalloow"
languagecode = "ko-KO"
paginate = 6
pluralizelisttitles = false
theme = "casper"
title = "Swalloow Blog"

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/"
weight = -120
[[menu.main]]
identifier = "personal"
name = "Personal"
url = "/personal"
weight = 100
[[menu.main]]
identifier = "develop"
name = "Develop"
url = "/develop"
weight = 101
[[menu.main]]
identifier = "datascience"
name = "Data Science"
url = "/datascience"
weight = 102
[[menu.main]]
identifier = "dataengineering"
name = "Data Engineering"
url = "/dataengineering"
weight = 109

[params]
author = "Swalloow"
authorlocation = "Seoul, Korea"
authorwebsite = "http://swalloow.github.io"
bio = "Interested in Data Science & Engineering"
cover = "images/cover_main.jpg"
description = "About Data Science & Data Engineering"
githubName = "Swalloow"
googleAnalyticsUserID = "UA-69281367-1"
hideHUGOSupport = false
logo = "images/logo.png"
twitterName = ""
[permalinks]
post = "/:slug/"

[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
