name: Build and Deploy
on:
  push:
    branches:
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"

      - name: Install and Build
        run: |
          yarn install
          npm run build
        env:
          SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          GOOGLE_ANALYTICS: ${{ secrets.GOOGLE_ANALYTICS }} 

      - name: Deploy to master
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
